Lab02_WebApplication3/Lab02_WebApplication3/Models/Song.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Lab02_WebApplication3.Models
{
    public class Song
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string url { get; set; }
        public string singer { get; set; }
        public Song()
        {

        }
        public Song(int ID, string Name, string url, string singer)
        {
            this.ID = ID;
            this.Name = Name;
            this.url = url;
            this.singer = singer;
        }
        public List<Song> getSong()
        {
            List<Song> songs = new List<Song>();
            songs.Add(new Song(1, "Chưa quên ngươi yêu cũ", "/Content/song/chuaquennguoiyeucu-hanhi.mp3", "Hà Nhi"));
            songs.Add(new Song(2, "Cô đơn trên sofa", "/Content/song/codontrensofa-trungquan.mp3", "Trung Quân"));
            songs.Add(new Song(3, "Khuất lối", "/Content/song/khuatloi-hkray.mp3", "H-Kray"));
            songs.Add(new Song(4, "Luôn yêu đời", "/Content/song/luonyeudoi-den.mp3", "Đen Vâu"));
            songs.Add(new Song(5, "Nàng thơ", "/Content/song/nangtho-hoangdung.mp3", "Hoàng Dũng"));
            songs.Add(new Song(6, "Người rất tốt không gặp sẽ tốt hơn", "/Content/song/nguoirattotkhonggapsetothon-hienho.mp3", "Hà Nhi"));
            songs.Add(new Song(7, "Nơi tình yêu bắt đầu", "/Content/song/noitinhyeubatdau-buianhtuan.mp3", "Bùi Anh Tuấn"));
            songs.Add(new Song(8, "Quả phụ tướng", "/Content/song/quaphutuong-dunghoangpham.mp3", "Dunghoangpham"));

            return songs;
        }
    }
}

Lab02_WebApplication3/Lab02_WebApplication3/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Lab02_WebApplication3.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Lab02_WebApplication3/Lab02_WebApplication3/Controllers/MusicController.cs
using Lab02_WebApplication3.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Lab02_WebApplication3.Controllers
{
    public class MusicController : Controller
    {
        // GET: Music
        Song s = new Song();
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult ListSong()
        {
            var songs = s.getSong();
            return View(songs);
        }
        public ActionResult Detail(int id)
        {
            var song = s.getSong().Where(st => st.ID == id).FirstOrDefault();
            ViewBag.Song = song;
            return View(song);
        }
        public FileContentResult Download(int id)
        {
            var song = s.getSong().Where(st => st.ID == id).FirstOrDefault();
            byte[] fileBytes = System.IO.File.ReadAllBytes(Server.MapPath(song.url));
            string fileName = song.Name + ".mp3";
            //return File(fileBytes, System.Net.Mime.MediaTypeNames.Application.Octet, fileName);
            return File(fileBytes, "audio/mp3", fileName);
        }
    }
}

Lab02_WebApplication3/Lab02_WebApplication3/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Styles.Render("https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse" title="more options">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Nhạc Việt Nam", "ListSong", "Music")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>